# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteResults', '0002_auto_20181017_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteguidelineresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiterulecategoryresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiterulescoperesult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
    ]
