# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteResults', '0004_auto_20180111_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteresult',
            name='group2_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ws_results', to='auditGroup2Results.AuditGroup2Result'),
        ),
        migrations.AlterField(
            model_name='websiteresult',
            name='group_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ws_results', to='auditGroupResults.AuditGroupResult'),
        ),
    ]
