# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-31 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteResults', '0005_auto_20181026_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteguidelineresult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteresult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiterulecategoryresult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiterulescoperesult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='websiteguidelineresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='websiteguidelineresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='websiteresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='websiteresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='websiterulecategoryresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='websiterulecategoryresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='websiteruleresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='websiteruleresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='websiterulescoperesult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='websiterulescoperesult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
    ]
