# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-08 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=1024)),
                ('scope', models.CharField(choices=[('All', 'All Users'), ('Sub', 'Users who have a paid subscription'), ('Free', "Users who's current account type is Free")], default='All', max_length=8)),
                ('status', models.CharField(choices=[('New', 'New Annoucement.'), ('Sending', 'Announcement is being sent through e-mail.'), ('Visible', 'Announcement is visible in web views.'), ('Arch', 'Announcement is only available in the archive.')], default='New', max_length=8)),
                ('email', models.BooleanField(default='True', verbose_name='E-mail to users')),
                ('web', models.BooleanField(default='True', verbose_name='Show in web views')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date for showing in web views')),
                ('message_text', models.TextField(default='')),
                ('message_markdown', models.TextField(blank=True, default='')),
                ('message_html', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=1024)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NR', 'No Response'), ('FB', 'Filed bug'), ('FFR', 'Filed feature enhancment'), ('R', 'Responded')], default='NR', max_length=128)),
                ('comments', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
