# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=1024)),
                ('scope', models.CharField(choices=[(b'All', b'All Users'), (b'Sub', b'Users who have a paid subscription'), (b'Free', b"Users who's current account type is Free")], default=b'All', max_length=8)),
                ('status', models.CharField(choices=[(b'New', b'New Annoucement.'), (b'Sending', b'Announcement is being sent through e-mail.'), (b'Visible', b'Announcement is visible in web views.'), (b'Arch', b'Announcement is only available in the archive.')], default=b'New', max_length=8)),
                ('email', models.BooleanField(default=b'True', verbose_name=b'E-mail to users')),
                ('web', models.BooleanField(default=b'True', verbose_name=b'Show in web views')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=b'End date for showing in web views')),
                ('message_text', models.TextField(default=b'')),
                ('message_markdown', models.TextField(blank=True, default=b'')),
                ('message_html', models.TextField(blank=True, default=b'')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=1024)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[(b'NR', b'No Response'), (b'FB', b'Filed bug'), (b'FFR', b'Filed feature enhancment'), (b'R', b'Responded')], default=b'NR', max_length=128)),
                ('comments', models.TextField(blank=True, default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
