# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroupResults', '0003_auto_20180111_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditgroupresult',
            options={'ordering': ['group_item'], 'verbose_name': 'Group Result', 'verbose_name_plural': 'Group Results'},
        ),
        migrations.AlterModelOptions(
            name='auditgroupruleresult',
            options={'ordering': ['rule'], 'verbose_name': 'Group Rule Result', 'verbose_name_plural': 'Group Rule Results'},
        ),
        migrations.AddField(
            model_name='auditgroupruleresult',
            name='websites_manual_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroupruleresult',
            name='websites_na',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroupruleresult',
            name='websites_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroupruleresult',
            name='websites_violation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroupruleresult',
            name='websites_warning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroupruleresult',
            name='websites_with_hidden_content',
            field=models.BigIntegerField(default=0),
        ),
    ]
