# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroupResults', '0003_auto_20181017_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroupguidelineresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroupresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgrouprulecategoryresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgrouprulescoperesult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
    ]
