# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroupResults', '0005_auto_20180117_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditgroupguidelineresult',
            options={'ordering': ['group_result__group_item'], 'verbose_name': 'Group Guideline Result', 'verbose_name_plural': 'Group Guideline Result'},
        ),
        migrations.AlterModelOptions(
            name='auditgrouprulecategoryresult',
            options={'ordering': ['group_result__group_item'], 'verbose_name': 'Group Rule Category Result', 'verbose_name_plural': 'Group Rule Category Results'},
        ),
        migrations.AlterModelOptions(
            name='auditgrouprulescoperesult',
            options={'ordering': ['group_result__group_item'], 'verbose_name': 'Group Rule Scope Result', 'verbose_name_plural': 'Group Rule Scope Results'},
        ),
    ]
