# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroupResults', '0007_auto_20181030_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroupguidelineresult',
            name='implementation_score_v',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='auditgroupguidelineresult',
            name='implementation_score_w',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='auditgroupresult',
            name='implementation_score_v',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='auditgroupresult',
            name='implementation_score_w',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='auditgrouprulecategoryresult',
            name='implementation_score_v',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='auditgrouprulecategoryresult',
            name='implementation_score_w',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='auditgroupruleresult',
            name='implementation_score_v',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='auditgroupruleresult',
            name='implementation_score_w',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='auditgrouprulescoperesult',
            name='implementation_score_v',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='auditgrouprulescoperesult',
            name='implementation_score_w',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
    ]
