# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rulesets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(max_length=512, verbose_name='Audit Title')),
                ('depth', models.IntegerField(choices=[(1, 'Start URL only'), (2, 'First level links'), (3, 'Second level links')], default=2)),
                ('max_pages', models.IntegerField(choices=[(5, '   5 pages'), (10, '  10 pages'), (25, '  25 pages'), (50, '  50 pages'), (100, ' 100 pages'), (200, ' 200 pages'), (400, ' 400 pages'), (800, ' 800 pages')], default=0, verbose_name='Maximum Pages')),
                ('wait_time', models.IntegerField(choices=[(30000, ' 30 seconds'), (45000, ' 45 seconds'), (60000, ' 60 seconds'), (90000, ' 90 seconds'), (120000, '120 seconds')], default=30000)),
                ('browser_emulation', models.CharField(choices=[('Firefox', 'Mozilla Firefox'), ('IE', 'Microsoft Internet Explorer'), ('Chrome', 'Google Chrome')], default='Chrome', max_length=32, verbose_name='Browser Emulation')),
                ('follow', models.IntegerField(choices=[(1, 'Specified domain only'), (2, 'Next-level subdomains')], default=1, verbose_name='Follow Links in')),
                ('frequency', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=32, verbose_name='Audit Frequency')),
                ('enable_audit', models.BooleanField(default=True, verbose_name='Enable Auditing')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rulesets.Ruleset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AuditGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(default='no group title', max_length=512, verbose_name='Group Title')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='audits.Audit')),
            ],
            options={
                'verbose_name': 'Audit Group',
                'verbose_name_plural': 'Audit Groups',
                'ordering': ['audit'],
            },
        ),
        migrations.CreateModel(
            name='AuditGroup2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(default='no group 2 title', max_length=512, verbose_name='Group 2 Title')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group2s', to='audits.Audit')),
            ],
            options={
                'verbose_name': 'Audit Group 2',
                'verbose_name_plural': 'Audit Group 2s',
                'ordering': ['audit'],
            },
        ),
        migrations.CreateModel(
            name='AuditGroup2Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(default='no group group item title', max_length=512, verbose_name='Group2 Item Title')),
                ('group2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group2_items', to='audits.AuditGroup2')),
            ],
            options={
                'verbose_name': 'Audit Group2 Item',
                'verbose_name_plural': 'Audit Groups2 Items',
                'ordering': ['group2', 'group_item'],
            },
        ),
        migrations.CreateModel(
            name='AuditGroupItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(default='no group item title', max_length=512, verbose_name='Group Item Title')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='audits.AuditGroup')),
            ],
            options={
                'verbose_name': 'Audit Group Item',
                'verbose_name_plural': 'Audit Groups Items',
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1024, verbose_name='Website URL')),
                ('title', models.CharField(default='no title', max_length=512, verbose_name='Website Title')),
                ('slug', models.SlugField(blank=True, max_length=128)),
                ('span_sub_domains', models.CharField(blank=True, default='', max_length=1024, verbose_name='Span Domains (space separated)')),
                ('exclude_sub_domains', models.CharField(blank=True, default='', max_length=1024, verbose_name='Exclude Domains (space separated)')),
                ('include_domains', models.CharField(blank=True, default='', max_length=1024, verbose_name='Include Domains (space separated)')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='audits.Audit')),
                ('group2_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='audits.AuditGroup2Item')),
                ('group_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='audits.AuditGroupItem')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'ordering': ['url'],
            },
        ),
        migrations.AddField(
            model_name='auditgroup2item',
            name='group_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group2_items', to='audits.AuditGroupItem'),
        ),
    ]
