# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroup',
            name='title_plural',
            field=models.CharField(default='no group plural title', max_length=512, verbose_name='Group Title'),
        ),
        migrations.AddField(
            model_name='auditgroup2',
            name='title_plural',
            field=models.CharField(default='no group2 plural title', max_length=512, verbose_name='Group Title'),
        ),
        migrations.AlterField(
            model_name='auditgroup2',
            name='title',
            field=models.CharField(default='no group2 title', max_length=512, verbose_name='Group 2 Title'),
        ),
    ]
