# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-17 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditgroup2',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditgroup2item',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditgroupitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
    ]
