# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auto_20180117_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditgroup',
            name='title_plural',
            field=models.CharField(default='no group plural title', max_length=512, verbose_name='Group Title Plural'),
        ),
        migrations.AlterField(
            model_name='auditgroup2',
            name='title_plural',
            field=models.CharField(default='no group2 plural title', max_length=512, verbose_name='Group 2 Title Plural'),
        ),
    ]
