# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20180203_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroupitem',
            name='abbreviation',
            field=models.CharField(default='no group item abbreviation', max_length=32, verbose_name='Group Item Abbreviation'),
        ),
        migrations.AddField(
            model_name='website',
            name='depth',
            field=models.IntegerField(choices=[(1, 'Start URL only'), (2, 'First level links'), (3, 'Second level links'), (4, 'Third level links'), (5, 'Fourth level links'), (6, 'Fifth level links')], default=2),
        ),
        migrations.AddField(
            model_name='website',
            name='follow',
            field=models.IntegerField(choices=[(1, 'Specified domain only'), (2, 'Next-level subdomains')], default=1, verbose_name='Follow Links in'),
        ),
        migrations.AddField(
            model_name='website',
            name='max_pages',
            field=models.IntegerField(choices=[(5, '   5 pages'), (50, '  50 pages'), (200, ' 200 pages'), (1000, '1000 pages'), (4000, '4000 pages')], default=200, verbose_name='Maximum Pages'),
        ),
        migrations.AddField(
            model_name='website',
            name='wait_time',
            field=models.IntegerField(choices=[(30000, ' 30 seconds'), (45000, ' 45 seconds'), (60000, ' 60 seconds'), (90000, ' 90 seconds'), (120000, '120 seconds')], default=60000),
        ),
        migrations.AlterField(
            model_name='audit',
            name='depth',
            field=models.IntegerField(choices=[(1, 'Start URL only'), (2, 'First level links'), (3, 'Second level links'), (4, 'Third level links'), (5, 'Fourth level links'), (6, 'Fifth level links')], default=2),
        ),
        migrations.AlterField(
            model_name='audit',
            name='max_pages',
            field=models.IntegerField(choices=[(5, '   5 pages'), (50, '  50 pages'), (200, ' 200 pages'), (1000, '1000 pages'), (4000, '4000 pages')], default=200, verbose_name='Maximum Pages'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='wait_time',
            field=models.IntegerField(choices=[(30000, ' 30 seconds'), (45000, ' 45 seconds'), (60000, ' 60 seconds'), (90000, ' 90 seconds'), (120000, '120 seconds')], default=60000),
        ),
    ]
