# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_auto_20180803_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroup2item',
            name='abbreviation',
            field=models.CharField(default='no group item abbreviation', max_length=32, verbose_name='Group Item Abbreviation'),
        ),
    ]
