# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroup2Results', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroup2result',
            name='website_count',
            field=models.IntegerField(default=0),
        ),
    ]
