# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroup2Results', '0002_auto_20180110_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroup2guidelineresult',
            name='has_manual_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditgroup2guidelineresult',
            name='implementation_pass_fail_summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2guidelineresult',
            name='implementation_summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2guidelineresult',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2result',
            name='has_manual_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditgroup2result',
            name='implementation_pass_fail_summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2result',
            name='implementation_summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2rulecategoryresult',
            name='has_manual_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditgroup2rulecategoryresult',
            name='implementation_pass_fail_summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2rulecategoryresult',
            name='implementation_summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2rulecategoryresult',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2rulescoperesult',
            name='has_manual_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditgroup2rulescoperesult',
            name='implementation_pass_fail_summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2rulescoperesult',
            name='implementation_summ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2rulescoperesult',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='elements_hidden',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='elements_mc_failed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='elements_mc_identified',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='elements_mc_na',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='elements_mc_passed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='elements_passed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='elements_violation',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='elements_warning',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='pages_with_hidden_content',
            field=models.BigIntegerField(default=0),
        ),
    ]
