# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroup2Results', '0003_auto_20180111_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='group2_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group2_rule_results', to='auditGroup2Results.AuditGroup2Result'),
        ),
    ]
