# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-17 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroup2Results', '0003_auditgroup2result_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditgroup2guidelineresult',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditgroup2result',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditgroup2rulecategoryresult',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditgroup2rulescoperesult',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=64),
        ),
    ]
