# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroup2Results', '0004_auto_20180112_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditgroup2result',
            options={'ordering': ['group2_item__title'], 'verbose_name': 'Group2 Result', 'verbose_name_plural': 'Group2 Results'},
        ),
        migrations.AlterModelOptions(
            name='auditgroup2ruleresult',
            options={'ordering': ['rule'], 'verbose_name': 'Group2 Rule Result', 'verbose_name_plural': 'Group2 Rule Results'},
        ),
        migrations.AddField(
            model_name='auditgroup2ruleresult',
            name='websites_manual_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2ruleresult',
            name='websites_na',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2ruleresult',
            name='websites_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2ruleresult',
            name='websites_violation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2ruleresult',
            name='websites_warning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2ruleresult',
            name='websites_with_hidden_content',
            field=models.BigIntegerField(default=0),
        ),
    ]
