# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroup2Results', '0004_auto_20181017_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroup2guidelineresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2result',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2rulecategoryresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditgroup2rulescoperesult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
    ]
