# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroup2Results', '0005_auto_20180116_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditgroup2ruleresult',
            options={'ordering': ['implementation_score'], 'verbose_name': 'Group2 Rule Result', 'verbose_name_plural': 'Group2 Rule Results'},
        ),
    ]
