# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditGroup2Results', '0005_auto_20181024_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditgroup2guidelineresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditgroup2guidelineresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditgroup2result',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditgroup2result',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditgroup2rulecategoryresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditgroup2rulecategoryresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditgroup2ruleresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditgroup2rulescoperesult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditgroup2rulescoperesult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
