# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageResults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageguidelineresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagerulecategoryresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagerulescoperesult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
    ]
