# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageResults', '0003_auto_20181025_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageguidelineresult',
            name='implementation_score_fail',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pageguidelineresult',
            name='implementation_score_mc',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pageguidelineresult',
            name='implementation_summ_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageresult',
            name='implementation_score_fail',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pageresult',
            name='implementation_score_mc',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pageresult',
            name='implementation_summ_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagerulecategoryresult',
            name='implementation_score_fail',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pagerulecategoryresult',
            name='implementation_score_mc',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pagerulecategoryresult',
            name='implementation_summ_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageruleresult',
            name='implementation_score_fail',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pageruleresult',
            name='implementation_score_mc',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pagerulescoperesult',
            name='implementation_score_fail',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pagerulescoperesult',
            name='implementation_score_mc',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='pagerulescoperesult',
            name='implementation_summ_fail',
            field=models.IntegerField(default=0),
        ),
    ]
