# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-31 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageResults', '0004_auto_20181026_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageguidelineresult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageresult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagerulecategoryresult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagerulescoperesult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pageguidelineresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pageguidelineresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pageresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pageresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pagerulecategoryresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pagerulecategoryresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pageruleresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pageruleresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pagerulescoperesult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pagerulescoperesult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
    ]
