# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditResults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='audit_directory',
            field=models.CharField(default='', max_length=1024, verbose_name='Data Directory'),
        ),
    ]
