# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditResults', '0002_auditresult_audit_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditresult',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=60),
        ),
    ]
