# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditResults', '0003_auto_20181017_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditguidelineresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditrulecategoryresult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditrulescoperesult',
            name='total_pages_pass_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='status',
            field=models.CharField(choices=[('-', 'Created'), ('I', 'Initalized'), ('A', 'Analyzing'), ('S', 'Saving Group Results'), ('C', 'Complete'), ('E', 'Error'), ('D', 'Marked for deletion')], default='-', max_length=10, verbose_name='Status'),
        ),
    ]
