# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditResults', '0004_auto_20181024_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditguidelineresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditguidelineresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditrulecategoryresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditrulecategoryresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditruleresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditruleresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditrulescoperesult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditrulescoperesult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
