# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditResults', '0005_auto_20180111_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditresult',
            options={'ordering': ['-created'], 'verbose_name': 'Audit Result', 'verbose_name_plural': 'Audit Results'},
        ),
        migrations.AlterModelOptions(
            name='auditruleresult',
            options={'ordering': ['-rule'], 'verbose_name': 'Audit Rule Result', 'verbose_name_plural': 'Audit Rule Results'},
        ),
        migrations.AlterModelOptions(
            name='auditrulescoperesult',
            options={'ordering': ['-rule_scope'], 'verbose_name': 'Audit Rule Scope Result', 'verbose_name_plural': 'Audit Rule Scope Results'},
        ),
        migrations.AddField(
            model_name='auditruleresult',
            name='websites_manual_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditruleresult',
            name='websites_na',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditruleresult',
            name='websites_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditruleresult',
            name='websites_violation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditruleresult',
            name='websites_warning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditruleresult',
            name='websites_with_hidden_content',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditguidelineresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='slug',
            field=models.SlugField(blank=True, default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='auditrulecategoryresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditrulescoperesult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
