# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-31 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditResults', '0006_auto_20181026_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditguidelineresult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditrulecategoryresult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditrulescoperesult',
            name='total_pages_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditguidelineresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditguidelineresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditrulecategoryresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditrulecategoryresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditruleresult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditruleresult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditrulescoperesult',
            name='implementation_pass_fail_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='auditrulescoperesult',
            name='implementation_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4),
        ),
    ]
