# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditResults', '0006_auto_20180116_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditruleresult',
            options={'ordering': ['implementation_score'], 'verbose_name': 'Audit Rule Result', 'verbose_name_plural': 'Audit Rule Results'},
        ),
    ]
