# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditResults', '0007_auto_20180117_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditresult',
            name='depth',
            field=models.IntegerField(choices=[(1, 'Start URL only'), (2, 'First level links'), (3, 'Second level links'), (4, 'Third level links'), (5, 'Fourth level links'), (6, 'Fifth level links')], default=2),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='max_pages',
            field=models.IntegerField(choices=[(5, '   5 pages'), (50, '  50 pages'), (200, ' 200 pages'), (1000, '1000 pages'), (4000, '4000 pages')], default=200, verbose_name='Maximum Pages'),
        ),
    ]
